dependencies:
  - name: kafka
    version: ^0.13.11
    repository: https://kubernetes-charts-incubator.storage.googleapis.com
    condition: kafka.enabled
  - name: elasticsearch
    version: ^1.11.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: elk.enabled
