kafka:
  enabled: true
  replicas: 3
  podAnnotations:
    sidecar.istio.io/inject: "false"
  zookeeper:
    enabled: true
    replicas: 3
    podAnnotations:
      sidecar.istio.io/inject: "false"
elk:
  enabled: true
elasticsearch:
  image:
    repository: "jhipster/jhipster-elasticsearch"
    tag: "v4.1.0"
  cluster:
    env:
      MINIMUM_MASTER_NODES: 2
  master:
    name: master
    replicas: 2
    podAnnotations:
      sidecar.istio.io/inject: "false"
  data:
    name: data
    replicas: 1
    podAnnotations:
      sidecar.istio.io/inject: "false"
  client:
    name: client
    replicas: 1
    podAnnotations:
      sidecar.istio.io/inject: "false"
