postgresql:
  enabled: true
  postgresqlUsername: gateway
  postgresqlDatabase: gateway
  master:
    podAnnotations:
      sidecar.istio.io/inject: "false"
  slave:
    podAnnotations:
      sidecar.istio.io/inject: "false"
